### ISSUE TITLE
Line Pay endpoint requirement

### ISSUE THREAD

**Issue by taylrj** [twreporter/go-api#287]
[This PR](https://github.com/taylrj/go-api/pull/1) includes fields required by line-pay that our go-api might need to support. Please have a see, @babygoat . Thanks.

**Comment by babygoat** [comment]
The return field `tappay_api_status` will be used to record both statuses in two steps transaction(e.g linepay). Thus, `0`, which stands for the success of the API request, might not infer the completeness of a transaction. Use our state field `status` would be more adequate.
