### ISSUE TITLE
Release Plan

### ISSUE THREAD

**Issue by howar31** [twreporter/go-api#584]
# Role Feature Deployment

## Schedule

- [x] 8/22 Feature toggle implementation (default false)
  - [x] Feature toggle off test on staging
  - [x] Feature toggle on test on staging
  - [x] Migration test on staging
- [x] 8/25 [go-api](https://github.com/twreporter/go-api/pull/595) production release
- [x] 8/25 [migration](https://github.com/twreporter/migration-history/tree/master/cloudsql/membership/update_roles) production release
- [x] 8/31 [cronjob](https://github.com/twreporter/cronjob/tree/master/mailchimp-sync) production release
- [x] 9/01 enable Feature toggle in production

## go-api Release

- Create a PR to merge the `staging` branch into the `release` branch

## Migration Release

1. Backup the database (or check the scheduled backup is up-to-date)
2. Connect to the database

```bash
gcloud sql connect twreporter-sql-db --user=membership_user --quiet
```

3. Run the migration script according to the [README](https://github.com/twreporter/migration-history/blob/master/cloudsql/membership/update_roles/README.md)

## Cronjob Release

mailchimp-sync cronjob is used for syncing DB mailing preferences to Mailchimp by API.   Deployment is documented in 
 [README](https://github.com/twreporter/cronjob/blob/master/mailchimp-sync/README.md).

## Feature Toggle

edit `configs/config.go`

```yaml
features:
    enable_rolemail: false
```

The role email feature is controlled by the `enable_rolemail` flag in the `configs/config.go` file.  It will be set to `false` by default.  To enable the role email feature, set the `enable_rolemail` flag to `true`.

- if `enable_rolemail` is `false` (default), then the role email feature is disabled.
- if `enable_rolemail` is `true`, then the role email feature is enabled.

When the feature is enabled, the role change email will be sent to the user's email address.  When the feature is disabled, the role change email will not be sent out.  Only log messages will be generated.

### Production Release

To enable the role email feature in production, set the `GOAPI_FEATURES_ENABLE_ROLEMAIL` to `true` in the [kubernetes-config](https://github.com/twreporter/kubernetes-config/blob/master/go-api/overlays/release/go-api.properties)

Trigger CircleCI pipeline (kubernetes kustomize)

**Comment by howar31** [comment]
@nickhsine @Aylie-Chou please review the Release Plan of the Role related features for go-api

**Comment by Aylie-Chou** [comment]
I think we might have to test feature toggle in staging before release.
In order to test it in staging, could @howar31  help to open the feature toggle in stagin ? (update staging config map setting in kubernetes-config repo, then re-deploy it)

**Comment by nickhsine** [comment]
In case that prod database migration fails, could we clone prod database data into staging database, and try all the operations listed in the release plan to make sure nothing missing here?

**Comment by howar31** [comment]
> I think we might have to test feature toggle in staging before release. In order to test it in staging, could @howar31 help to toggle the feature toggle in staging ? (depend on the testing schedule, updating staging config map setting in kubernetes-config repo, then re-deploy it)

The feature toggle on/off testing on staging is completed.
![image](https://github.com/twreporter/go-api/assets/880459/7e9696db-b53b-43f1-8ec2-49bf36e0f3b2)
![image](https://github.com/twreporter/go-api/assets/880459/f6985c02-652e-4a7e-b61c-c2143cbc3bd7)
